### ISSUE TITLE
[Question] Is there a need to re-pull and recreate toolbox images periodically?

### ISSUE THREAD

**Issue by abceleung** [toolbx-images/images#114]
Hi, I want to use the Debian Sid toolbox image with Distrobox. 
Since Sid is a rolling release distro, running `apt update && apt upgrade` should be enough to keep the container updated, right? Is there any benefit to re-pulling and recreating the image?
Also, in case of non-rolling distro images like Debian Stable, what is the best way to upgrade from one release to another: performing the upgrade inside the container or re-pull and recreate?

**Comment by travier** [comment]
In general, when you update in place, the image gets bigger on the disk as the new files from updated packages are added to the container.

If you re-pull and re-create from an updated image then you will use less storage but will "waste" network bandwitdh. Both options work.

It's up to you to decide what's the best for you.
