### ISSUE TITLE
Withdraw distribution: Red Hat Enterprise Linux or RHEL

### ISSUE THREAD

**Issue by debarshiray** [toolbx-images/images#118]
### Distribution name and versions requested

Red Hat Enterprise Linux or RHEL all versions (including 7, 8.2, 8.4, 8.6, 8.8, 9.0, 9.2, 9.3)

### Where are the official container images from the distribution published?

The sources for the UBI-based toolbox images published for Red Hat Enterprise Linux at [registry.access.redhat.com/ubi8/toolbox:8.9](https://catalog.redhat.com/software/containers/ubi8/toolbox/611bd665bd674341b5c5ed46) and [such](https://catalog.redhat.com/software/containers/ubi9/toolbox/61532d7dd2c7f84a4d2ed86b) are already available from [github.com/containers/toolbox](https://github.com/containers/toolbox/tree/main/images/rhel).  These are the images that are used with Toolbx's built-in support for RHEL through `--distro rhel`, and are tested and supported accordingly by Red Hat.

The images included in this repository are different, and introduce a second set of images for RHEL.  It will be good if we can avoid this confusion and point users to the canonical set.

Note that Toolbx never advertised support for RHEL 7.x and RHEL <  8.5, and the official image for RHEL 9.0 was broken because it was published with the wrong tag (ie., 9.0.0 instead of 9.0).  Hence, those are missing from [github.com/containers/toolbox](https://github.com/containers/toolbox/tree/main/images/rhel).

### Will you be interested in maintaining this image?

n/a

**Comment by debarshiray** [comment]
I see that the RHEL images here have the [Extra Packages for Enterprise Linux](https://docs.fedoraproject.org/en-US/epel/) repository enabled.  One alternative I can image is to offer something like an Ansible playbook that lowers the barrier to enabling EPEL.  Will that work?

**Comment by debarshiray** [comment]
Submitted a pull request: https://github.com/toolbx-images/images/pull/120

**Comment by travier** [comment]
Fixed by https://github.com/toolbx-images/images/pull/120.
