### ISSUE TITLE
Withdraw distribution: Fedora

### ISSUE THREAD

**Issue by debarshiray** [toolbx-images/images#119]
### Distribution name and versions requested

Fedora all versions (including 38, 39 and 40)

### Where are the official container images from the distribution published?

The sources for the `fedora-toolbox` images published for Fedora at `registry.fedoraproject.org/fedora-toolbox` have always been available from [github.com/containers/toolbox](https://github.com/containers/toolbox/tree/main/images/fedora), and, historically, from Fedora's own infrastructure at [src.fedoraproject.org/container/fedora-toolbox](https://src.fedoraproject.org/container/fedora-toolbox).   These are the images that are used with Toolbx's built-in support for Fedora through `--distro fedora`, and are tested and supported accordingly.

The `fedora-toolbox` image was [rewritten](https://src.fedoraproject.org/container/fedora-toolbox/blob/rawhide/f/dead.container) as part of the [ToolbxReleaseBlocker](https://fedoraproject.org/wiki/Changes/ToolbxReleaseBlocker) Change for Fedora 39 to make it part of the Fedora's nightly composes and a release-blocking deliverable.  The image might get rewritten [again](https://fedoraproject.org/wiki/Changes/KiwiBuiltCloudImages) soon.  Due to this ongoing churn, we have held off from updating [github.com/containers/toolbox](https://github.com/containers/toolbox/tree/main/images/fedora) for Fedora >= 39.

The images included in this repository are different, and introduce a second set of images for Fedora.  It will be good if we can avoid this confusion and point users to the canonical set.

### Will you be interested in maintaining this image?

n/a

**Comment by debarshiray** [comment]
The [README.md](https://github.com/toolbx-images/images/blob/main/README.md) claims that these `fedora-toolbox` images are:
*slightly smaller alternatives to the official Fedora images*.

Looking at the [commit](https://github.com/toolbx-images/images/commit/032e747a02f274123c20aca8629608d07d25961d) that introduced them, it seems that the trigger was [this](https://github.com/redhat-imaging/imagefactory/issues/412) Image Factory bug that [blew up](https://bugzilla.redhat.com/show_bug.cgi?id=2245066) the sizes of the official images for Fedora >= 39.  However, that bug was fixed within two weeks of someone noticing it, and before Fedora 39 was released.

Today, the claim of being *slightly smaller alternatives* doesn't seem to hold.  The alternative `fedora-toolbox` images in this repository are consistently bigger than the ones at `registry.fedoraproject.org`.

Fedora 38:
```ShellSession
$ toolbox create --release 38
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:38 (333.8MB)? [y/N]: 

$ toolbox create --image quay.io/toolbx-images/fedora-toolbox:38
Image required to create toolbox container.
Download quay.io/toolbx-images/fedora-toolbox:38 (373.4MB)? [y/N]:
```

Fedora 39:
```ShellSession
$ toolbox create --release 39
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:39 (359.8MB)? [y/N]: 

$ toolbox create --image quay.io/toolbx-images/fedora-toolbox:39
Image required to create toolbox container.
Download quay.io/toolbx-images/fedora-toolbox:39 (393.9MB)? [y/N]:
```

Fedora 40:
```ShellSession
$ toolbox create --release 40
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:40 (360.8MB)? [y/N]:

$ toolbox create --image quay.io/toolbx-images/fedora-toolbox:40
Image required to create toolbox container.
Download quay.io/toolbx-images/fedora-toolbox:40 (386.5MB)? [y/N]: 
```

**Comment by debarshiray** [comment]
Submitted a pull request: https://github.com/toolbx-images/images/pull/121

**Comment by travier** [comment]
Fixed with https://github.com/toolbx-images/images/pull/121
