### ISSUE TITLE
opensuse-toolbox:tumbleweed diffutils conflict

### ISSUE THREAD

**Issue by lethedata** [toolbx-images/images#130]
### Image and version of the image where the issue happens

opensuse-toolbox:tumbleweed

### Describe the bug

Unable to enter image due to error installing basic packages.
```
Problem: 1: the installed busybox-diffutils-1.36.1-32.2.noarch conflicts with 'diffutils' provided by the to be installed diffutils-3.10-1.7.x86_64
 Solution 1: deinstallation of busybox-diffutils-1.36.1-32.2.noarch
 Solution 2: do not install diffutils-3.10-1.7.x86_64
```

This might have been introduced by commit https://github.com/toolbx-images/images/commit/513c8ed7a5442eb6ff9474ab0b3d436014412db5 once suse added busybox-diffutils.

### Reproduction steps

1. `distrobox create --image opensuse-toolbox:tumbleweed --name tumbleweed`
2. `distrobox enter tumbleweed`

### Host distribution and version, toolbx and podman versions

- Fedora Linux 40 (Silverblue)
- distrobox: 1.7.2.1
- podman version 5.1.2

**Comment by travier** [comment]
Does this help? https://github.com/toolbx-images/images/pull/133

**Comment by lethedata** [comment]
> Does this help? #133

Sorry for taking a bit to get to this, yes it worked.
