### ISSUE TITLE
Cleaning up Ubuntu images from `toolbx-images/ubuntu-toolbox` repo

### ISSUE THREAD

**Issue by Jmennius** [toolbx-images/images#135]
Since we've moved Ubuntu images to the upstream repo, we've also moved Ubuntu images to the `toolbx/ubuntu-toolbox` as well.
Images in `toolbx-images/ubuntu-toolbox` repo are still there (but outdated) and people might sometimes refer to them which is confusing.
See containers/toolbox#1566 for example. Although it is most likely the the distribution hardcoded that repo into the package - I will check this.

**Comment by travier** [comment]
I was waiting before doing it but this feels like the right time now indeed. Let's do it.

**Comment by travier** [comment]
![arch_pulls](https://github.com/user-attachments/assets/37cbe48c-6b66-49ec-8153-afad4f7fac7e)
![ubuntu_pulls](https://github.com/user-attachments/assets/fa7b68e8-61b1-4367-b845-c129934cc733)

We're going to get bug reports 🙃

**Comment by travier** [comment]
Done

**Comment by Jmennius** [comment]
Ooops :)
I guess I need to figure out the things with Ubuntu package ASAP then 😅

**Comment by travier** [comment]
I've made https://github.com/toolbx-images/images/pull/136 to make the README a bit more explicit.
