### ISSUE TITLE
Alpine edge image build failure

### ISSUE THREAD

**Issue by travier** [toolbx-images/images#137]
### Image and version of the image where the issue happens

Alpine Edge

### Describe the bug

See: https://github.com/toolbx-images/images/actions/runs/11883651456/job/33110735792

```
ERROR: net-tools-doc-2.10-r3: trying to overwrite usr/share/man/man1/hostname.1.gz owned by uutils-coreutils-doc-0.0.28-r2.
```

### Reproduction steps

See CI above

### Host distribution and version, toolbx and podman versions

N/A

**Comment by castrojo** [comment]
Usually with a rolling release it works itself out by just waiting, I'll chase this one down though! I PRed removing the EOL alpine images: https://github.com/toolbx-images/images/pull/138 which should catch us up. Thanks!

**Comment by castrojo** [comment]
>  ✅ Successfully pushed "alpine-toolbox:edge" to "quay.io/toolbx-images/alpine-toolbox:edge"

Rebuild did the trick!

**Comment by travier** [comment]
Thanks!
