### ISSUE TITLE
Move to podman/buildah based actions

### ISSUE THREAD

**Issue by travier** [toolbx-images/images#46]
We can use:
- https://github.com/redhat-actions/buildah-build
- https://github.com/redhat-actions/push-to-registry

for the build and push actions instead of the Docker actions so that have a podman only stack (from image builds to toolbx).

**Comment by Foxboron** [comment]
I think this is a good idea :)

**Comment by debarshiray** [comment]
Yes, please.  :)

**Comment by travier** [comment]
The reason why I've not done this change everywhere yet is that I could not find a clear way of doing multi-arch images with the podman/buildah actions.
