### ISSUE TITLE
Should we update and regularly rebuild the images or not?

### ISSUE THREAD

**Issue by travier** [toolbx-images/images#5]
Right now, the Containerfiles do not update the packages in the image.

We have two options:
- Keep the Containerfiles as is (users will update them on first run anyway) and remove all weekly rebuilds as they won't change the image.
- Update the Containerfiles to make sure that they update the packages and trigger rebuilds every two weeks (weekly seems to much).

Note: This discussion apply to Arch Linux too but we need to keep it updated monthly at miminum.

**Comment by Foxboron** [comment]
I'd perfer weekly rebuilds for Arch as we are dealing with work containers.

**Comment by travier** [comment]
Any particular reason for weekly rebuilds? Do you re-create one every week? Then if that's the case do you re-install all your tools there every time? Then I'd say that maybe you're better served by having your own container build from another repo on top of this one. I have mine in https://github.com/travier/quay-containerfiles/tree/main/toolbox for example that builds on top of the Fedora one.

I would say that the target for those images is people that create an image and update it over time instead of re-creating it all the time.

**Comment by Foxboron** [comment]
Packages update fast in Arch. If you create a new container at the tailend of the month then a lot of those packages are going to be old. It's better to use `toolbox create` and know the container isn't super outdated.

**Comment by travier** [comment]
OK, let's do weekly rebuilt. I hope we'll have enough built minutes.

**Comment by HarryMichal** [comment]
The same reasoning for periodical rebuilds can also apply to Fedora Rawhide.

**Comment by travier** [comment]
Agree that Rawhide should be rebuilt regularly. Is this not the case right now?

**Comment by travier** [comment]
Note that most of the images here do not update the packages. I'm looking at that in https://github.com/toolbx-images/images/pull/20

**Comment by travier** [comment]
Looks like I read https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions incorrectly and actions minutes are free and unlimited for public projects. I will turn builds on in PRs.

**Comment by HarryMichal** [comment]
> Agree that Rawhide should be rebuilt regularly. Is this not the case right now?

All Fedora Toolbx images are being rebuilt regularly. I mainly mentioned it to support the need for Arch Linux images to be rebuilt regularly.

**Comment by Jmennius** [comment]
I think Ubuntu images should be rebuilt bi-weekly but at least once a month.

**Comment by travier** [comment]
Then they need some work like I did in https://github.com/toolbx-images/images/commit/52a51d545bbe2881c13d122e1d07e59b8c667581 for the CentOS ones as right now they don't update at all.

**Comment by travier** [comment]
Well, they do get updated but only if the base image is updated.

**Comment by travier** [comment]
https://github.com/toolbx-images/images/pull/41 should close this one.

**Comment by travier** [comment]
See discussion in https://github.com/toolbx-images/images/pull/41, we'll not update Debian & Ubuntu images.
Maybe we revisit the discussion here and not update all images by default.

**Comment by debarshiray** [comment]
> > Agree that Rawhide should be rebuilt regularly. Is this not the case right now?
> 
> All Fedora Toolbx images are being rebuilt regularly. I mainly mentioned it to support the need for Arch Linux images to be rebuilt regularly.

Just to be clear ...

These days, [since](https://fedoraproject.org/wiki/Changes/ToolbxReleaseBlocker) the Fedora 39 development cycle, the `fedora-toolbox` image for Rawhide gets built as part of the nightly composes.  Earlier, they were being manually rebuilt every few weeks, just like the images for the stable Fedora releases.

Currently, the built-in `arch-toolbox` and `ubuntu-toolbox` images, maintained as part of [Toolbx](https://github.com/containers/toolbox), are rebuilt every Monday.

**Comment by travier** [comment]
Let's close this one as I don't think there is anything more to do.
