### ISSUE TITLE
Consider removing NAME and VERSION variables

### ISSUE THREAD

**Issue by Jmennius** [toolbx-images/images#50]
This was previously discussed in containers/toolbox#188.
Those variables are not required for non-Fedora images as it is only used by OSBS to build Fedora images.
Otherwise, they just pollute user environment and the upstream project got a few complaints about that.

I suggest we remove them as thy provide no value (that is not otherwise covered by labels) and cause some annoyance.

**Comment by travier** [comment]
If toolbox does not need them then let's do it 👍🏻
