### ISSUE TITLE
openSUSE build failures

### ISSUE THREAD

**Issue by travier** [toolbx-images/images#57]
### Image and version of the image where the issue happens

OpenSUSE (latest)

### Describe the bug

See https://github.com/toolbx-images/images/actions/workflows/opensuse.yaml

### Reproduction steps

N/A

### Host distribution and version, toolbx and podman versions

N/A

**Comment by TheEvilSkeleton** [comment]
I'm not sure why it's failing. It successfully built locally by those commands:
```
podman build -t test-opensuse -f Containerfile
toolbox create -c test --image opensuse-test
toolbox enter test
```

I don't understand the error either.

**Comment by travier** [comment]
OK, that's weird then. Will take another look soon.

**Comment by TheEvilSkeleton** [comment]
This seems to work now. Should we close it?

**Comment by travier** [comment]
We indeed have a successful build! Thanks
