### ISSUE TITLE
Error pulling candidate quay.io/toolbx-images/ubuntu-toolbox:20.04

### ISSUE THREAD

**Issue by rickyrsyah** [toolbx-images/images#60]
### Image and version of the image where the issue happens

ubuntu-toolbox:20.04

### Describe the bug

DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user rickyrsyah 
DEBU Validating sub-ID file /etc/subuid           
DEBU Validating sub-ID file /etc/subgid           
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Migrating to newer Podman                    
DEBU Toolbox config directory is /home/rickyrsyah/.config/toolbox 
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called version.PersistentPreRunE(podman --log-level debug version --format json) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/rickyrsyah/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/rickyrsyah/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/rickyrsyah/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/rickyrsyah/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Called version.PersistentPostRunE(podman --log-level debug version --format json) 
DEBU Current Podman version is 4.3.1              
DEBU Creating runtime directory /run/user/1000/toolbox 
DEBU Old Podman version is 4.3.1                  
DEBU Migration not needed: Podman version 4.3.1 is unchanged 
DEBU Setting up configuration                     
DEBU Setting up configuration: file /home/rickyrsyah/.config/containers/toolbox.conf not found 
DEBU Resolving image name                         
DEBU Distribution (CLI): ''                       
DEBU Image (CLI): ''                              
DEBU Release (CLI): ''                            
DEBU Resolved image name                          
DEBU Image: 'fedora-toolbox:37'                   
DEBU Release: '37'                                
DEBU Resolving container name                     
DEBU Container: ''                                
DEBU Image: 'fedora-toolbox:37'                   
DEBU Release: '37'                                
DEBU Resolved container name                      
DEBU Container: 'fedora-toolbox-37'               
DEBU Resolving image name                         
DEBU Distribution (CLI): ''                       
DEBU Image (CLI): 'quay.io/toolbx-images/ubuntu-toolbox:20.04' 
DEBU Release (CLI): ''                            
DEBU Resolved image name                          
DEBU Image: 'quay.io/toolbx-images/ubuntu-toolbox:20.04' 
DEBU Release: '20.04'                             
DEBU Resolving container name                     
DEBU Container: ''                                
DEBU Image: 'quay.io/toolbx-images/ubuntu-toolbox:20.04' 
DEBU Release: '20.04'                             
DEBU Resolved container name                      
DEBU Container: 'ubuntu-toolbox-20.04'            
DEBU Checking if container ubuntu-toolbox-20.04 already exists 
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called exists.PersistentPreRunE(podman --log-level debug container exists ubuntu-toolbox-20.04) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/rickyrsyah/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/rickyrsyah/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/rickyrsyah/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/rickyrsyah/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Called exists.PersistentPostRunE(podman --log-level debug container exists ubuntu-toolbox-20.04) 
DEBU Looking for image quay.io/toolbx-images/ubuntu-toolbox:20.04 
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called exists.PersistentPreRunE(podman --log-level debug image exists quay.io/toolbx-images/ubuntu-toolbox:20.04) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/rickyrsyah/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/rickyrsyah/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/rickyrsyah/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/rickyrsyah/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Looking up image "quay.io/toolbx-images/ubuntu-toolbox:20.04" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "quay.io/toolbx-images/ubuntu-toolbox:20.04" ... 
DEBU[0000] Trying "quay.io/toolbx-images/ubuntu-toolbox:20.04" ... 
DEBU[0000] Trying "quay.io/toolbx-images/ubuntu-toolbox:20.04" ... 
DEBU[0000] Called exists.PersistentPostRunE(podman --log-level debug image exists quay.io/toolbx-images/ubuntu-toolbox:20.04) 
Image required to create toolbox container.
Download quay.io/toolbx-images/ubuntu-toolbox:20.04 (500MB)? [y/N]: y
DEBU Pulling image quay.io/toolbx-images/ubuntu-toolbox:20.04 
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called pull.PersistentPreRunE(podman --log-level debug pull quay.io/toolbx-images/ubuntu-toolbox:20.04) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/rickyrsyah/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/rickyrsyah/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/rickyrsyah/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/rickyrsyah/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Pulling image quay.io/toolbx-images/ubuntu-toolbox:20.04 (policy: always) 
DEBU[0000] Looking up image "quay.io/toolbx-images/ubuntu-toolbox:20.04" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "quay.io/toolbx-images/ubuntu-toolbox:20.04" ... 
DEBU[0000] Trying "quay.io/toolbx-images/ubuntu-toolbox:20.04" ... 
DEBU[0000] Trying "quay.io/toolbx-images/ubuntu-toolbox:20.04" ... 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf" 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Attempting to pull candidate quay.io/toolbx-images/ubuntu-toolbox:20.04 for quay.io/toolbx-images/ubuntu-toolbox:20.04 
DEBU[0000] parsed reference into "[overlay@/home/rickyrsyah/.local/share/containers/storage+/run/user/1000/containers]quay.io/toolbx-images/ubuntu-toolbox:20.04" 
Trying to pull quay.io/toolbx-images/ubuntu-toolbox:20.04...
DEBU[0000] Copying source image //quay.io/toolbx-images/ubuntu-toolbox:20.04 to destination image [overlay@/home/rickyrsyah/.local/share/containers/storage+/run/user/1000/containers]quay.io/toolbx-images/ubuntu-toolbox:20.04 
DEBU[0000] Using registries.d directory /etc/containers/registries.d 
DEBU[0000] Trying to access "quay.io/toolbx-images/ubuntu-toolbox:20.04" 
DEBU[0000] No credentials matching quay.io/toolbx-images/ubuntu-toolbox found in /run/user/1000/containers/auth.json 
DEBU[0000] No credentials matching quay.io/toolbx-images/ubuntu-toolbox found in /home/rickyrsyah/.config/containers/auth.json 
DEBU[0000] No credentials matching quay.io/toolbx-images/ubuntu-toolbox found in /home/rickyrsyah/.docker/config.json 
DEBU[0000] No credentials matching quay.io/toolbx-images/ubuntu-toolbox found in /home/rickyrsyah/.dockercfg 
DEBU[0000] No credentials for quay.io/toolbx-images/ubuntu-toolbox found 
DEBU[0000]  No signature storage configuration found for quay.io/toolbx-images/ubuntu-toolbox:20.04, using built-in default file:///home/rickyrsyah/.local/share/containers/sigstore 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/quay.io 
DEBU[0000] GET https://quay.io/v2/                      
DEBU[0007] Ping https://quay.io/v2/ status 401          
DEBU[0007] GET https://quay.io/v2/auth?scope=repository%3Atoolbx-images%2Fubuntu-toolbox%3Apull&service=quay.io 
DEBU[0009] Increasing token expiration to: 60 seconds   
DEBU[0009] GET https://quay.io/v2/toolbx-images/ubuntu-toolbox/manifests/20.04 
DEBU[0010] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.list.v2+json" 
DEBU[0010] Using blob info cache at /home/rickyrsyah/.local/share/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0010] Source is a manifest list; copying (only) instance sha256:fc60a1147771b86742fd5d371c514a80407be6b184f3b76164c51456bf62a292 for current system 
DEBU[0010] GET https://quay.io/v2/toolbx-images/ubuntu-toolbox/manifests/sha256:fc60a1147771b86742fd5d371c514a80407be6b184f3b76164c51456bf62a292 
DEBU[0012] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.v2+json" 
DEBU[0012] IsRunningImageAllowed for image docker:quay.io/toolbx-images/ubuntu-toolbox:20.04 
DEBU[0012]  Using default policy section                
DEBU[0012]  Requirement 0: allowed                      
DEBU[0012] Overall: allowed                             
DEBU[0012] Downloading /v2/toolbx-images/ubuntu-toolbox/blobs/sha256:4cf12e3eb337eb5b099df7836bdf174595fac0b384d5d2b6d3301058dcd45949 
DEBU[0012] GET https://quay.io/v2/toolbx-images/ubuntu-toolbox/blobs/sha256:4cf12e3eb337eb5b099df7836bdf174595fac0b384d5d2b6d3301058dcd45949 
Getting image source signatures
DEBU[0031] Reading /home/rickyrsyah/.local/share/containers/sigstore/toolbx-images/ubuntu-toolbox@sha256=fc60a1147771b86742fd5d371c514a80407be6b184f3b76164c51456bf62a292/signature-1 
DEBU[0031] Not looking for sigstore attachments: disabled by configuration 
DEBU[0031] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0031] ... will first try using the original manifest unmodified 
DEBU[0031] Checking if we can reuse blob sha256:846c0b181fff0c667d9444f8378e8fcfa13116da8d308bf21673f7e4bea8d580: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Checking if we can reuse blob sha256:0dbba1558eaf2408a7ed6e126e1fd97e711ea87198a508018f58b37e486939fe: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Checking if we can reuse blob sha256:8d90b2d9584880369ddffabf86ac33946a874bfd8c602729e90cbbbea902ee0b: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Checking if we can reuse blob sha256:954bca2c43d34fc00f0ebeabad88a095ac90468d48a8d1c10e9e7fd5d31cf7da: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Checking if we can reuse blob sha256:b2959aa7e8865914a0e368c008f3689fb55b6e0418f354217a020a557629ee6f: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Checking if we can reuse blob sha256:a9b9f2b8530955b52ed2ec8cdfed610159eadc41a8507c7ce706f1b25e7b6b02: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Skipping blob sha256:0dbba1558eaf2408a7ed6e126e1fd97e711ea87198a508018f58b37e486939fe (already present): 
Copying blob 0dbba1558eaf skipped: already exists  
DEBU[0031] Failed to retrieve partial blob: blob type not supported for partial retrieval 
DEBU[0031] Downloading /v2/toolbx-images/ubuntu-toolbox/blobs/sha256:8d90b2d9584880369ddffabf86ac33946a874bfd8c602729e90cbbbea902ee0b 
DEBU[0031] GET https://quay.io/v2/toolbx-images/ubuntu-toolbox/blobs/sha256:8d90b2d9584880369ddffabf86ac33946a874bfd8c602729e90cbbbea902ee0b 
DEBU[0031] Checking if we can reuse blob sha256:7328eae5ff20a42d7a4e5f8a06a30b42c3dbcaeb4be73451b6ad119f2e49f4bd: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Skipping blob sha256:954bca2c43d34fc00f0ebeabad88a095ac90468d48a8d1c10e9e7fd5d31cf7da (already present): 
DEBU[0031] Checking if we can reuse blob sha256:d8f20e85d10bcb9802b8d8efe9d8e71e013e543e8b78a59d239e2d3fac5cc84e: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Failed to retrieve partial blob: blob type not supported for partial retrieval 
DEBU[0031] Skipping blob sha256:b2959aa7e8865914a0e368c008f3689fb55b6e0418f354217a020a557629ee6f (already present): 
DEBU[0031] Downloading /v2/toolbx-images/ubuntu-toolbox/blobs/sha256:d8f20e85d10bcb9802b8d8efe9d8e71e013e543e8b78a59d239e2d3fac5cc84e 
DEBU[0031] GET https://quay.io/v2/toolbx-images/ubuntu-toolbox/blobs/sha256:d8f20e85d10bcb9802b8d8efe9d8e71e013e543e8b78a59d239e2d3fac5cc84e 
DEBU[0031] Skipping blob sha256:846c0b181fff0c667d9444f8378e8fcfa13116da8d308bf21673f7e4bea8d580 (already present): 
DEBU[0031] Checking if we can reuse blob sha256:9f61bc0d8d47bedf04db44dbfcd35378c5a842131b2d3b53c23cd43132577e63: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0031] Failed to retrieve partial blob: blob type not supported for partial retrieval 
DEBU[0031] Downloading /v2/toolbx-images/ubuntu-toolbox/blobs/sha256:9f61bc0d8d47bedf04db44dbfcd35378c5a842131b2d3b53c23cd43132577e63 
DEBU[0031] GET https://quay.io/v2/toolbx-images/ubuntu-toolbox/blobs/sha256:9f61bc0d8d47bedf04db44dbfcd35378c5a842131b2d3b53c23cd43132577e63 
DEBU[0031] Failed to retrieve partial blob: blob type not supported for partial retrieval 
DEBU[0031] Downloading /v2/toolbx-images/ubuntu-toolbox/blobs/sha256:7328eae5ff20a42d7a4e5f8a06a30b42c3dbcaeb4be73451b6ad119f2e49f4bd 
DEBU[0031] GET https://quay.io/v2/toolbx-images/ubuntu-toolbox/blobs/sha256:7328eae5ff20a42d7a4e5f8a06a30b42c3dbcaeb4be73451b6ad119f2e49f4bd 
DEBU[0031] Failed to retrieve partial blob: blob type not supported for partial retrieval 
DEBU[0031] Downloading /v2/toolbx-images/ubuntu-toolbox/blobs/sha256:a9b9f2b8530955b52ed2ec8cdfed610159eadc41a8507c7ce706f1b25e7b6b02 
DEBU[0031] GET https://quay.io/v2/toolbx-images/ubuntu-toolbox/blobs/sha256:a9b9f2b8Copying blob 0dbba1558eaf skipped: already exists  
Copying blob 8d90b2d95848 [--------------------------------------] 0.0b / 131.7MiB
Copying blob 0dbba1558eaf skipped: already exists  
Copying blob 8d90b2d95848 [--------------------------------------] 0.0b / 131.7MiB
Copying blob 0dbba1558eaf skipped: already exists  
Copying blob 8d90b2d95848 [>-------------------------------------] 4.9MiB / 131.7MiB
Copying blob 0dbba1558eaf skipped: already exists  
Copying blob 8d90b2d95848 [=>------------------------------------] 5.3MiB / 131.7MiB
Copying blob 954bca2c43d3 skipped: already exists  
Copying blob b2959aa7e886 skipped: already exists  
Copying blob 0dbba1558eaf skipped: already exists  
Copying blob 8d90b2d95848 [===================================>] 131.7MiB / 131.7MiB
Copying blob 954bca2c43d3 skipped: already exists  
Copying blob b2959aa7e886 skipped: already exists  
Copying blob d8f20e85d10b done  
Copying blob 846c0b181fff skipped: already exists  
Copying blob 9f61bc0d8d47 done  
Copying blob 7328eae5ff20 done  
Copying blob a9b9f2b85309 done  
DEBU[0089] Error pulling candidate quay.io/toolbx-images/ubuntu-toolbox:20.04: copying system image from manifest list: writing blob: storing blob to file "/var/tmp/storage1736393385/2": happened during read: unexpected EOF 
Error: copying system image from manifest list: writing blob: storing blob to file "/var/tmp/storage1736393385/2": happened during read: unexpected EOF
Error: failed to pull image quay.io/toolbx-images/ubuntu-toolbox:20.04
If it was a private image, log in with: podman login quay.io
Use 'toolbox --verbose ...' for further details.

### Reproduction steps

toolbox --verbose create --image quay.io/toolbx-images/ubuntu-toolbox:20.0
4

### Host distribution and version, toolbx and podman versions

Linux fedora 6.1.6-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 14 16:55:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
toolbox version 0.0.99.3
podman version 4.3.1

**Comment by travier** [comment]
I can not reproduce this issue. I can pull this image and create a toolbox container. I'd recommend checking disk space, disk errors, cleaning podman image cache, etc.
