### ISSUE TITLE
The ubuntu-toolbox:18.04 image is substantially smaller

### ISSUE THREAD

**Issue by debarshiray** [toolbx-images/images#72]
### Image and version of the image where the issue happens

Ubuntu 18.04

### Describe the bug

I finally got around to trying to merge https://github.com/containers/toolbox/pull/483 to offer built-in support for Ubuntu, when I noticed that compared to the `ubuntu-toolbox` image for other versions, the `ubuntu-toolbox:18.04` image is substantially smaller.  As per `skopeo inspect` it's 68.98MB, while the others are approximately 160MB.

I haven't checked if something is wrong or broken, but the size difference jumped out at me.

### Reproduction steps

With Toolbx from Git `main`:
```
[rishi@topinka toolbox]$ toolbox create --image quay.io/toolbx-images/ubuntu-toolbox:18.04
Image required to create toolbox container.
Download quay.io/toolbx-images/ubuntu-toolbox:18.04 (68.98MB)? [y/N]: N
[rishi@topinka toolbox]$ 
[rishi@topinka toolbox]$ 
[rishi@topinka toolbox]$ toolbox create --image quay.io/toolbx-images/ubuntu-toolbox:16.04
Image required to create toolbox container.
Download quay.io/toolbx-images/ubuntu-toolbox:16.04 (158.3MB)? [y/N]: N
[rishi@topinka toolbox]$ 
[rishi@topinka toolbox]$ toolbox create --image quay.io/toolbx-images/ubuntu-toolbox:20.04
Image required to create toolbox container.
Download quay.io/toolbx-images/ubuntu-toolbox:20.04 (166.1MB)? [y/N]: N
[rishi@topinka toolbox]$ 
[rishi@topinka toolbox]$ toolbox create --image quay.io/toolbx-images/ubuntu-toolbox:22.04
Image required to create toolbox container.
Download quay.io/toolbx-images/ubuntu-toolbox:22.04 (158.3MB)? [y/N]: N
```

### Host distribution and version, toolbx and podman versions

Toolbx from Git `main`, and Skopeo >= 1.10.0

**Comment by travier** [comment]
Thanks for testing it. I'm not sure we'll do more if it works like that. 18.04 is too old now.

**Comment by Jmennius** [comment]
It appears the issue is that 18.04 Containerfile is due to missing `ubuntu-minimal`, `ubuntu-standard` for some reason (instead it's in the FIXME - I have no idea why).
And apparently that's the reason we experience #73 and consequently #74 is not required.
Opened #75.

**Comment by debarshiray** [comment]
> It appears the issue is that 18.04 Containerfile is due to missing `ubuntu-minimal`, `ubuntu-standard` for some reason (instead it's in the FIXME - I have no idea why). And apparently that's the reason we experience #73 and consequently #74 is not required. Opened #75.

The Git history says that `/usr/local/sbin/unminimize`, `ubuntu-minimal` and `ubuntu-standard` were removed from `ubuntu-toolbox:18.04` in commit [5cbaecde2f30ea1d](https://github.com/toolbx-images/images/commit/5cbaecde2f30ea1d82ba186662353d19b5ec685b) to fix the build.
