### ISSUE TITLE
New Package: libcap2-bin - Ubuntu 18.04

### ISSUE THREAD

**Issue by debarshiray** [toolbx-images/images#73]
### To which distribution image and which version should we add this package?

Ubuntu 18.04

### Why should we include this package by default?

The `ubuntu-toolbox:18.04` doesn't work at the moment because `capsh(1)` is absent.

The container gets created:
```
$ toolbox create --image quay.io/toolbx-images/ubuntu-toolbox:18.04
Image required to create toolbox container.
Download quay.io/toolbx-images/ubuntu-toolbox:18.04 (68.98MB)? [y/N]: y
Created container: ubuntu-toolbox-18.04
Enter with: toolbox enter ubuntu-toolbox-18.04
```

... but it can't be entered:
```
$ toolbox --verbose enter ubuntu-toolbox-18.04
...
Error: crun: executable file `capsh` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
...
```

`dpkg -S bin/capsh` on other Ubuntu versions indicate that the `libcap2-bin` package provides `capsh(1)`.

**Comment by neuhaus** [comment]
The toolbox for Ubuntu 22.04 also needs this package

**Comment by travier** [comment]
Please report that to https://github.com/containers/toolbox as the Ubuntu toolbox images have been moved there.
