### ISSUE TITLE
Withdraw distribution: Ubuntu

### ISSUE THREAD

**Issue by debarshiray** [toolbx-images/images#81]
### Distribution name and versions requested

Ubuntu all versions (including 16.04, 18.04, 20.04, 22.04 and 22.10).

### Where are the official container images from the distribution published?

See: https://github.com/containers/toolbox/pull/483

The sources for the Ubuntu images are now being maintained at [github.com/containers/toolbox](https://github.com/containers/toolbox/tree/main/images/ubuntu), and are slowly [starting](https://github.com/containers/toolbox/pull/1291) to [diverge](https://github.com/containers/toolbox/pull/1292) from the sources in this repository.  Therefore, it might be time to withdraw the old sources from here.

Note that the Ubuntu images are still being consumed from `quay.io/toolbx-images`.  We might be changing it to `quay.io/toolbx` in the near future, but until that happens the built images shouldn't be withdrawn from the registry.

### Will you be interested in maintaining this image?

n/a

**Comment by travier** [comment]
This has been merged.
