### ISSUE TITLE
Add distribution: Debian 12 (bookworm)

### ISSUE THREAD

**Issue by starquake** [toolbx-images/images#86]
### Distribution name and versions requested

Debian 12 (Bookworm)

### Where are the official container images from the distribution published?

https://hub.docker.com/_/debian

### Will you be interested in maintaining this image?

Yes, but I'm using distrobox

**Comment by pennbauman** [comment]
I am interested in becoming a maintainer for this image. I am also currently a distrobox user, but I am hoping to switch to toolbx and this is the only thing I still need to do that.
